---
kind: pipeline
#type: kubernetes
name: default

metadata:
  namespace: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master

steps:

- name: named
  image: plugins/docker
  settings:
    repo: docker.io/kanatakita/named
    tags: latest
    context: named
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: debug
  image: plugins/docker
  settings:
    repo: docker.io/kanatakita/debug
    tags: latest
    context: debug
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: dumper
  image: plugins/docker
  settings:
    repo: docker.io/kanatakita/dumper
    tags: latest
    context: dumper
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

